version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '27081:80'
    container_name: wxcloud_wyvernriderbackendnodejs
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=wyvernriderbackendnodejs
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=4TnaynvF
      - MYSQL_ADDRESS=10.31.100.86:3306
      - MYSQL_USERNAME=dolphinux
      - MYSQL_PASSWORD=jarLOVE123
networks:
  default:
    external:
      name: wxcb0
